networks:
  minio:
    driver: bridge

version: '3.6'
services:
  minio-gateway:
    image: 'uzumlukek/minio-gateway:latest'
    container_name: minio-gateway
    command:
      'gateway s3 https://s3.amazonaws.com:443 -address "0.0.0.0:9000"'
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      MINIO_ROOT_USER: 'gateway-user'
      MINIO_ROOT_PASSWORD: 'gateway-password'
    expose:
      - 9000
    healthcheck:
      test: curl --fail http://localhost:9000/minio/health/live || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    networks:
      - minio

  minio-gateway-test:
    depends_on:
      minio-gateway:
        condition: service_started
    image: 'uzumlukek/minio-mc:latest'
    entrypoint: >
      /bin/sh -c "
      mc alias set remote http://minio-gateway:9000 gateway-user gateway-password;
      mc cp remote/muhammed-minio/muhammed.jpeg ~/localbucket
      "
    networks:
      - minio


  minio-server:
    depends_on:
      minio-gateway:
        condition: service_started
    image: 'uzumlukek/minio:latest'
    entrypoint: >
      /bin/sh -c "
      minio server /data --console-address 0.0.0.0:9090;
      "
    ports:
      - "8080:9090"
      - "9000:9000"
    expose:
      - 9000
      - 9090
    environment:
      MINIO_ROOT_USER: "server-user"
      MINIO_ROOT_PASSWORD: "server-password"
    volumes:
      - /var/lib/minio/:/data
    healthcheck:
      test: curl --fail http://localhost:9000/minio/health/ready || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    networks:
      - minio


  minio-server-fillup:
    depends_on:
      minio-server:
        condition: service_started
    image: 'uzumlukek/minio-mc:latest'
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio-server:9000 server-user server-password;
      mc alias set remote http://minio-gateway:9000 gateway-user gateway-password;
      mc mb local/muhammed-minio/ -p;
      mc mirror remote/muhammed-minio local/muhammed-minio;
      mc ls local/muhammed-minio;
      "
    networks:
      - minio


